apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all resources to
namespace: mingtong-test

resources:
- web-app

# all with following *kustomization*
images:
- name: mingtong/web-app
  newName: 432127183358.dkr.ecr.us-east-2.amazonaws.com/mingtong/web-app
  newTag: fb8fb6e3cee9ac62352db03f46de296cb4aee05a
